[build]
  command = "cd netlify/functions && npm install"
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  publish = "static"
  functions = "netlify/functions"
  targetPort = 8000