[build]
  command = "cd netlify/functions && npm install"
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python main.py"
  port = 8000
  publish = "static" 